import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const hemiHead = localFont({
  src: "./fonts/hemi head bd it.ttf",
});

const playRegular = localFont({
  src: "./fonts/Play-Regular.ttf",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${hemiHead.className} ${playRegular.className}`}>
        
          {children}
       
      </body>
    </html>
  );
}
